// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    InputText: typeof import('./components/InputText.vue')['default']
    ListBlockCountry: typeof import('./components/ListBlockCountry.vue')['default']
    ListBlockCountryCode: typeof import('./components/ListBlockCountryCode.vue')['default']
    ListBlockIP: typeof import('./components/ListBlockIP.vue')['default']
    ModalError: typeof import('./components/ModalError.vue')['default']
    ModalNewApp: typeof import('./components/ModalNewApp.vue')['default']
    ModalProjectInput: typeof import('./components/ModalProjectInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableProjectLists: typeof import('./components/TableProjectLists.vue')['default']
    TableTd: typeof import('./components/TableTd.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheDivider: typeof import('./components/TheDivider.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TheNavbar: typeof import('./components/TheNavbar.vue')['default']
    TheSwitcher: typeof import('./components/TheSwitcher.vue')['default']
    TheTitle: typeof import('./components/TheTitle.vue')['default']
  }
}
